### ISSUE TITLE
not all icons show

### ISSUE THREAD

**Issue by cutepanda12** [tech-advantage/ngx-icon-picker#10]
I am on 4.7.0 - Not all of the icons show, it stops at the 'Meetup'
How do I hide all the ones that are blank?

![a](https://user-images.githubusercontent.com/42588922/44430211-fb3b9280-a567-11e8-9502-8248c6551a67.PNG)

**Comment by greg7859** [comment]
Hi,
I check with our example. All icons are displayed : 
![image](https://user-images.githubusercontent.com/4975282/44464227-81181600-a61a-11e8-985e-4d6642d5adae.png)

Could you test with our example ?
It based on font Awesome ^4.7.0 and Angular ^5.2.0

**Comment by greg7859** [comment]
After meetup, we display glyphicon icons. Do you use it ?

**Comment by cutepanda12** [comment]
I am using Angular 6.0.1 - is that the issue?

**Comment by alexvazquezfente** [comment]
Use the following component input as documented in the README:
[ipIconPack]="'fa'"
