### ISSUE TITLE
auto show icon picker

### ISSUE THREAD

**Issue by cutepanda12** [tech-advantage/ngx-icon-picker#11]
how to show icon picker with having to click on input or a button?

**Comment by cutepanda12** [comment]
hello, can someone please help me with this?

**Comment by greg7859** [comment]
Hello,
The icon selector is displayed when you click on input component.
Can you check than you follow the readme to integrate this component in your application?
Can you send us an exam which reproduce your problem?

**Comment by cutepanda12** [comment]
I just want the icon-picker and icon-grid class. Is there a way not to use 'input' in the code? Because I don't want to click on the input. i just want to show the grid.

**Comment by greg7859** [comment]
In this issue, we explain how to use the icon-picker with the tag **<A>**: https://github.com/tech-advantage/ngx-icon-picker/issues/2

You can adapt this example to display the grid without click in input.
