### ISSUE TITLE
New Font Awsome Version

### ISSUE THREAD

**Issue by ongun23** [tech-advantage/ngx-icon-picker#12]
Is there any script or solution to upgrade the latest version of Font Awsome?

**Comment by ongun23** [comment]
Any update or development progress for this issue?

**Comment by NoelToy** [comment]
Please look into this https://github.com/NoelToy/ngx-icon-picker-fontawesome5

**Comment by greg7859** [comment]
@NoelToy Thank to help us to improve this library. So, are you ok to push a PR into this repository?

**Comment by NoelToy** [comment]
@greg7859 Sure, will do within 2 days.
