### ISSUE TITLE
No available option found to set the icon width and height

### ISSUE THREAD

**Issue by MoEffat** [tech-advantage/ngx-icon-picker#17]
Hello,

It would be really nice if we can add a new option like [ipWidth] to set the icons size inside the dialog box. The actual icons size is too small and a manual zoom in is needed for some users to identify an icon. 

Thanks in advance,

**Comment by greg7859** [comment]
Hello,

This proposal is an excellent idea. I will propose an improvement in a few minutes.

**Comment by greg7859** [comment]
Could you test this PR?
If you valid it, I will deploy this new version.

**Comment by BallisticPain** [comment]
I'm excited to see the icon size can be configured!! I simply added this in my CSS (along with an override attribute on the body tag to give me the specificity).

```
[override] .icon-picker div.icon-grid div button {
  width: 42px !important;
  padding: 2px !important;

  span {
    font-size: 2em;
  }
}
```

**Comment by greg7859** [comment]
I added a new property `ipIconSize` to override the default values.
I don't test to override it with CSS.

Today, I will deploy this new version on npm .

**Comment by greg7859** [comment]
This version is deployed on npm. Open an issue if you have a problem.
