### ISSUE TITLE
icons are no more justified and aligned in version 1.0.0 compared to 0.0.11

### ISSUE THREAD

**Issue by MoEffat** [tech-advantage/ngx-icon-picker#21]
First, many thanks for the new version :)

The new **[ipIconSize]** parameter works perfectly 

Now another issue occured. The icons are no more justified and aligned like they were on the version 0.0.11.

Please find in attachment 2 screenshots to show you the difference between the 2 versions.
For your information in the version 1.0.0 the ipIconSize was not provided, so by default icons are not aligned.

version 0.0.11 with perfect icons alignment:
![version_0 0 11](https://user-images.githubusercontent.com/61591429/77100477-ffff4b80-6a15-11ea-9d21-701442f80d2b.png)

version 1.0.0 with random icons alignment
![version_1 0 0](https://user-images.githubusercontent.com/61591429/77100501-05f52c80-6a16-11ea-83f6-64db740a2cf7.png)

**Comment by BallisticPain** [comment]
Not sure this is helpful, but below is what I used to make my icons bigger before the 1.0 release. 
Also, it may need a `fa-fw` to make the width fixed... looks like the `fa5` icon set. (It's what I'm using).

The `override` attribute I placed on my `<body>` tag ... `<body override>`
```
[override] .icon-picker div.icon-grid div button {
  width: 42px !important;
  padding: 2px !important;

  span {
    font-size: 2em;
  }
}
```

**Comment by MoEffat** [comment]
Hello @BallisticPain 

I confirm that your solution to add an override attribute works fine. The icons are bigger and aligned. I just would prefer using the ipIconSize without extra css

**Comment by greg7859** [comment]
The button size is computed according to the icon size and the padding. I added a new property `ipIconPadding` to change the padding if need. The default is 6px like before.

**Comment by greg7859** [comment]
This issue is available on the 1.1.0 released on npm

**Comment by MoEffat** [comment]
Hello, Thanks for the new version,

I am facing a new minor issue though! Some icon buttons do not have the same height. Please find below a screenshot from version 1.1.0. Can you make sure that all icon buttons have the same height.

![icon_button_smaller](https://user-images.githubusercontent.com/61591429/77207486-c43db200-6af9-11ea-912a-163757e9010c.png)

**Comment by greg7859** [comment]
I didn't reproduce the problem but I modified the component to set the width and height of the button.
I added the horizontal (left/right) and vertical (top/bottom) padding to improve the padding control

**Comment by greg7859** [comment]
Release 1.1.1

**Comment by BallisticPain** [comment]
@greg7859 That looks good. Thanks for the efforts!

@MoEffat I totally understand the desire to use the component without *special* overrides. I provided that to give the example of how I made the icons be the same size. I played with the CSS for a little while before arriving at those values.

**Comment by MoEffat** [comment]
@greg7859 The version 1.1.1 looks perfect for me :+1: 

@BallisticPain Many thanks for the css solution, for your information I was using it until now ;-)
