### ISSUE TITLE
Enhancement: Specify classes instead of bootstrap

### ISSUE THREAD

**Issue by Thorski** [tech-advantage/ngx-icon-picker#25]
Very nice picker, thank you.

For those like myself not using bootstrap classes, it would be nice to be able to specify these classes instead of having them hard coded:
  btn btn-default form-control input-sm
and any others I missed :)

For the icons in the grid I realize I can style them with ip-button-icon.   It just would be a tad more convenient to use classes I already have.

For the input box there is no way to style it (unless I define form-control and input-sm classes).
Ideally I would like to be able to pass classes that will be used.

Thank you!

**Comment by Thorski** [comment]
Add: customizable font size in search box.

**Comment by greg7859** [comment]
Could you send me an example to valid the change?

**Comment by Thorski** [comment]
something like 
  [ipStyleClass]="myButtonStyles"     // define classes for buttons instead of btn btn-default
  [ipSearchStyleClass]="mySearchStyles"  // define classes for search box instead of form-control

And make sure can override the font size, right now it is hard because
.icon-picker * {
  box-sizing: border-box;
  margin: 0;
  font-size: 11px;
}

Maybe take it out of icon-picker so mySearchStyles can override it, or add a ipSearchFont?

-- Thor

**Comment by greg7859** [comment]
Ok, I thought you wanted to use another framework like bulma, semantic, ...

I will try to do that in a cup of days

**Comment by greg7859** [comment]
I added 3 parameters:
* [ipButtonStyleClass] to override the class for the button.
* [ipDivSearchStyleClass] to override the class for the div search
* [ipInputSearchStyleClass] to override the class for the input search

To explain how to use it, I created 2 examples:
* app-bulma
* app-semantic

For both, I use the framework to replace boostrap

Do you to test this change?

**Comment by Thorski** [comment]
Sure!   How do I test it?

Thanks!!

**Comment by greg7859** [comment]
To test, you have to clone this repository and checkout the branch issue-25. 
Then, go to in the repository folder (for example /tmp/ngx-icon-picker) and type `npm install` and `npm run build` 
The library will be build

Go in your project and type `npm install /tmp/ngx-icon-picker`. The 1.2.0 will be installed in your project.

Hope it helps you!

**Comment by Thorski** [comment]
Thank you it works very well.
It is still hard to overwrite the hard coded 11px size in the .icon-picker
class due to view encapsulation.  I have to use important.

[ipInputSearchStyleClass]="'my-input-search1'"

.my-input-search1 {
  font-size: 1rem !important;
}

Thank you!

**Comment by greg7859** [comment]
I removed the .icon-picker * declaration in scss file.

Could you tell me if it works in your case?

**Comment by Thorski** [comment]
Works great thank you

**Comment by greg7859** [comment]
This version (1.2.0) was deployed on npmjs repository. 
Enjoy it!

**Comment by Thorski** [comment]
Thank you so much!
