### ISSUE TITLE
[Feature Request] FontAwesome6 Icon pack

### ISSUE THREAD

**Issue by michaelmarcuccio** [tech-advantage/ngx-icon-picker#51]
FontAwesome 6 has released and there is no pack for it. Is there a way to do that by manually supplying an icon package that isn't included?

**Comment by greg7859** [comment]
I added the FA6 support in https://github.com/tech-advantage/ngx-icon-picker/tree/fontawesome-6

I just declared 2 icons for test, let me know if you are ok with it. I will complete the pack in the future.

**Comment by greg7859** [comment]
I added FA6 icons in the release 1.11.2. 
Only solid icons are added.

**Comment by stpp2** [comment]
Awesome, thank you!
As a sidenote/idea - FontAwesome claims there's 100% backwards compatibility between FA6 and FA5 icons, so I assumed that just extending it would work.

(FWIW, you can still use the `fa5` pack while actually installing the latest `font-awesome` 6.x lib to display all the fa6 icons that existed in fa5)
