### ISSUE TITLE
Html file cannot be found

### ISSUE THREAD

**Issue by vgogov** [tech-advantage/ngx-icon-picker#6]
Hello,

Thanks for this project. I'm currently also using the Color Picker module as well. Although when I try this package out by importing the module and inserting the icon-picker in my html as follows:

`  <input [iconPicker]="icon" (iconPickerSelect)="onIconPickerSelect(newIcon)"/> `

But it fails saying: 

```
core.es5.js:1084 ERROR Error: Uncaught (in promise): Failed to load icon-picker.component.html
    at resolvePromise (zone.js:683) [angular]
    at /polyfills.bundle.js:940:17 [angular]
    at Object.onInvokeTask (core.es5.js:4116) [angular]
```

Any ideas? Thanks!

**Comment by mijankowski** [comment]
same problem..

**Comment by greg7859** [comment]
Hello,
We reproduce the problem.
Work in progress ;)

**Comment by mijankowski** [comment]
Fixed.
thanks
