### ISSUE TITLE
Improve package.json

### ISSUE THREAD

**Issue by IBlackI** [tech-advantage/ngx-icon-picker#60]
The current package.json does not follow the recommendations by Angular.  https://angular.io/guide/creating-libraries#peer-dependencies. It would be best to move some of the dependencies to peerDependencies.

Furthermore some of the dependencies are marked using the `~` operator meaning they only allow increments in patch versions. The example below only accepts `12.0.x` however it should use the `^` operator to accept all angular 12 packages.
https://github.com/tech-advantage/ngx-icon-picker/blob/e16c6a8787431b4e18fb35f16a7c0ad530e7f092/package.json#L22
This causes issues for projects to install this package.

**Comment by greg7859** [comment]
Deploy on npmjs.

Release: 1.10.0
