### ISSUE TITLE
[opPosition] works incorrectly with form inside modal

### ISSUE THREAD

**Issue by pr0menade** [tech-advantage/ngx-icon-picker#7]

**Comment by greg7859** [comment]
Hello pr0menade,

I tried to reproduce the problem, but it works for me. I added some code in the example to help you to integrate the icon picker in the modal dialog.

Hope this will help you.

**Comment by greg7859** [comment]
Argh, I forgot to check the opPosition...

**Comment by greg7859** [comment]
After checking, it works too.

Be careful, it 's **[ipPosition]** and not **[opPosition]**

Try with this code : 
` <input type="text" name="iconCss" class="form-control" formControlName="iconCss" [iconPicker]="icon" [ipPosition]="'top'"
          [ipWidth]="'250px'" [ipPlaceHolder]="'Choose an icon'" [ipFallbackIcon]="fallbackIcon" (iconPickerSelect)="onIconPickerSelect($event)"
        />`
