### ISSUE TITLE
update for angular 16?

### ISSUE THREAD

**Issue by TahsinAhmedz** [tech-advantage/ngx-icon-picker#80]
Hi, angular 16 doesn't seem to be compatible with the latest version of ngx-icon-picker, will there be any update in the future for ngx-icon-picker to make it compatible?

**Comment by greg7859** [comment]
The version 1.11.0 is compatible with Angular 16.

Warning : I removed the boostrap glyphicon
The app example use Bootstrap 4.

The library is available : https://www.npmjs.com/package/ngx-icon-picker
